name: Build ESP32-S3 IDF v6.0.2

on:
  push:
    branches: [ main, feat/music-player ]
  pull_request:
    branches: [ main ]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 编译工程
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: "v6.0.2"
          target: "esp32s3"

      - name: 上传固件产物
        uses: actions/upload-artifact@v4
        with:
          name: ESP32S3-firmware-bin
          path: build/*.bin
